name: Publish Notepadtt to Dockerhub Slow

on:
  workflow_dispatch:
    inputs:
      SemVer:
        description: 'Semantic Version of the release'
        required: true

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
    - name: Validate Version
      run: |
        VERSION=${{ github.event.inputs.SemVer }}
        if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format: $VERSION"
          exit 1
        else
          echo "Valid version format: $VERSION"
        fi
  
  release:
    needs: validate-version
    runs-on: ubuntu-latest
    environment:
      name: docker-url
      url: https://hub.docker.com/r/joshtxdev/notepadtt
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: joshtxdev/notepadtt
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        platforms: linux/amd64,linux/arm64
        tags: latest,${{ github.event.inputs.SemVer }}